services:
  - type: web
    name: dental-cbct-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 1
    envVars:
      - key: ROBOFLOW_API_KEY
        value: luFuyH88RAQnCmLZoWCp
      - key: PYTHON_VERSION
        value: 3.11.9
